!devrock.releasing.model.configuration.ReleaseConfiguration
  repositoryPrototype: !com.braintribe.devrock.model.repository.IndexedMavenHttpRepository
      name: "hiconic-os-release"

  includes:
    - "com.braintribe.common:*"
    - "com.braintribe.asm:*"
    - "com.braintribe.wire:*"
    - "com.braintribe.archives:*"
    - "com.braintribe.logging:*"
    - "com.braintribe.templatetools:*"
    - "com.braintribe.testing:*"
    - "com.braintribe.web.multipart:*"
    - "com.braintribe.concurrency:*"
    - "com.braintribe.execution:*"
    - "com.braintribe.jdom2:*"
    - "com.braintribe.saxon:*"
    - "com.braintribe.systemtools:*"
    - "com.braintribe.tomcat:*"
    - "com.braintribe.xml:*"
    - "com.braintribe.codec:*"
    - "com.braintribe.htmltools:*"
    - "com.braintribe.security:*"
    - "com.braintribe.servlet:*"
    - "com.braintribe.velocity:*"
